dev:
  url: https://automationexercise.com/
  username:
  password:
  baseURI:
  service_username:
  service_password:
  database:
  dbService:
  pool: 5
  dbUsername:
  dbPassword:
  seleniumGridUrl: http://localhost:4444/wd/hub
test:
  url: https://automationexercise.com/
  username:
  password:
  baseURI:
  service_username:
  service_password:
  database:
  dbService:
  pool: 5
  dbUsername:
  dbPassword:
  seleniumGridUrl: http://localhost:4444/wd/hub
staging:
  url:
  username:
  password:
  baseURI:
  service_username:
  service_password:
  database:
  dbService:
  pool: 5
  dbUsername:
  dbPassword:
  seleniumGridUrl: http://localhost:4444/wd/hub